#spring:
#  data:
#    mongodb:
#      authentication-database: admin
#      uri: mongodb://admin:lin2890343180@localhost:27017
#      database:
server:
  port: 8081

spring:
  servlet:
    multipart.max-file-size: 10MB
    max-request-size: 10MB

# Swagger UI Customization
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

# Swagger UI Customization
apiTitle: "RunWu API"
apiDescription: "An accessible platform to share art works & ideas. See the GitHub page for more information at (https://github.com/lijiaxi2018/runwu)"
apiVersion: "0.1"