server:
  port: 8081

spring:
  servlet:
    multipart.max-file-size: 10MB
    max-request-size: 10MB

# Swagger UI Customization
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

# Swagger UI Customization
apiTitle: "RunWu API"
apiDescription: "An accessible platform to share art works & ideas. See the GitHub page for more information at (https://github.com/lijiaxi2018/runwu)"
apiVersion: "0.1"

# Data Directory
path:
  uploads: "./src/main/resources/uploads/"
  users: "./src/main/resources/uploads/users/"

file:
  upload:
#    location: /src/main/resources/uploads/
    location: /backend/src/main/resources/uploads/